create extension if not exists pgcrypto;
create table if not exists categories(id uuid primary key default gen_random_uuid(),name text not null,sort_order int default 0,active boolean default true,created_at timestamptz default now());
create table if not exists products(id uuid primary key default gen_random_uuid(),category_id uuid references categories(id) on delete set null,name text not null,price text,description text,sizes text[] default '{}',images text[] default '{}',active boolean default true,created_at timestamptz default now());
alter table categories enable row level security;
alter table products enable row level security;
create policy "public categories" on categories for select using (active=true);
create policy "public products" on products for select using (active=true);
create policy "auth categories" on categories for all to authenticated using(true) with check(true);
create policy "auth products" on products for all to authenticated using(true) with check(true);
insert into categories(name,sort_order) values('Jeans',1),('Camisetas',2),('Bermudas',3),('Tênis',4),('Calças',5);
insert into storage.buckets(id,name,public) values('product-images','product-images',true) on conflict(id) do update set public=true;
create policy "public images" on storage.objects for select using(bucket_id='product-images');
create policy "auth upload" on storage.objects for insert to authenticated with check(bucket_id='product-images');
create policy "auth delete" on storage.objects for delete to authenticated using(bucket_id='product-images');
